-- Denný agent — Supabase DB schema.
--
-- Tento súbor bol donedávna zastaraný stub (obsahoval iba dodatočne
-- pridanú tabuľku agent_memory, nie celú schému) — nahradené 2026-09-18
-- zavedením poriadnej migračnej histórie, aby už nevznikal rozdiel medzi
-- týmto súborom a realitou v Supabase.
--
-- Aktuálny stav schémy: supabase/migrations/0001_baseline_2026-09-18.sql
-- + všetky ďalšie číslované súbory v supabase/migrations/ (pozri README.md
-- tamtiež pre postup pri ďalších zmenách).
--
-- Chronologická história zmien (prečo/kedy pribudlo ktoré pole): PROJECT.md
-- v projektových dokumentoch (claude/schema.sql tam obsahuje rovnaký
-- aktuálny stav ako baseline + migrácie tu).
